subMatrix.CFA.object <- function(simMatrixSet, ...) { #loading, latent.cor, error.cor, latent.var = NULL, error.var = NULL, indicator.var = NULL, intercept = NULL, indicator.mean = NULL, factor.mean = NULL) {
	W <- get.keywords()
	if(simMatrixSet@Tag != "CFA") stop("The simMatrixSet tag is not CFA.")
	List <- list(...)
	Names <- names(List)
	keywords <- list(W$loading, W$error, W$latent.cor, c("Variance of Measurement Error", W$VTD, W$VTE), c("Variance of Indicators", W$VX, W$VY), W$intercept, W$factor.mean, c("Means of Indicators", W$MX, W$MY), c("Variance of Factors", W$VE, W$VPS, W$VPH))
	position <- match.keyword(Names, keywords)
	if(length(position) != length(unique(position))) stop("Some objects were identified more than once.")
	ifelse(contain(1, position), ifelse(!is.null.object(simMatrixSet@LY), LY <- List[position == 1], stop("LY is not indicated in simMatrixSet.")), LY <- list(new("nullSimMatrix")))
	ni <- nrow(run(simMatrixSet@LY[[1]]))
	nk <- ncol(run(simMatrixSet@LY[[1]]))
	ifelse(contain(2, position), ifelse(!is.null.object(simMatrixSet@TE), TE <- List[position == 2], stop("TE is not indicated in simMatrixSet.")), TE <- list(new("nullSymMatrix")))
	ifelse(contain(3, position), ifelse(!is.null.object(simMatrixSet@PS), PS <- List[position == 3], stop("PS is not indicated in simMatrixSet.")), PS <- list(new("nullSymMatrix")))
	ifelse(contain(4, position), ifelse(!is.null.object(simMatrixSet@VTE), VTE <- List[position == 4], stop("VTE is not indicated in simMatrixSet.")), VTE <- list(new("nullSimVector")))
	ifelse(contain(5, position), ifelse(!is.null.object(simMatrixSet@VY), VY <- List[position == 5], stop("VY is not indicated in simMatrixSet.")), VY <- list(new("nullSimVector")))
	ifelse(contain(8, position), ifelse(!is.null.object(simMatrixSet@MY), MY <- List[position == 8], stop("MY is not indicated in simMatrixSet.")), MY <- list(new("nullSimVector")))
	ifelse(contain(6, position), ifelse(!is.null.object(simMatrixSet@TY), TY <- List[position == 6], stop("TY is not indicated in simMatrixSet.")), TY <- list(new("nullSimVector")))
	ifelse(contain(7, position), ifelse(!is.null.object(simMatrixSet@ME), ME <- List[position == 7], stop("ME is not indicated in simMatrixSet.")), ME <- list(new("nullSimVector")))
	ifelse(contain(9, position), ifelse(!is.null.object(simMatrixSet@VE), VE <- List[position == 9], stop("VE is not indicated in simMatrixSet.")), VE <- list(new("nullSimVector")))
	Output <- new("subMatrixSet", LY=LY[[1]], PS=PS[[1]], TE=TE[[1]], VE=VE[[1]], VPS=VE[[1]], VTE=VTE[[1]], VY=VY[[1]], TY=TY[[1]], MY=MY[[1]], ME=ME[[1]], AL=ME[[1]], Tag="CFA")
	return(Output)
}
