misspecified.CFA.object <- function(...) { #loading, latent.cor, error.cor, latent.var = NULL, error.var = NULL, indicator.var = NULL, intercept = NULL, indicator.mean = NULL, factor.mean = NULL) {
	W <- get.keywords()
	List <- list(...)
	Names <- names(List)
	keywords <- list(W$loading, W$error, W$latent.cor, c("Variance of Measurement Error", W$VTD, W$VTE), c("Variance of Indicators", W$VX, W$VY), W$intercept, W$factor.mean, c("Means of Indicators", W$MX, W$MY), c("Variance of Factors", W$VE, W$VPS, W$VPH))
	position <- match.keyword(Names, keywords)
	if(length(position) != length(unique(position))) stop("Some objects were identified more than once.")
	ifelse(contain(1, position), LY <- List[position == 1], LY <- list(new("nullSimMatrix")))
	ifelse(contain(2, position), TE <- List[position == 2], TE <- list(new("nullSymMatrix")))
	ifelse(contain(3, position), PS <- List[position == 3], PS <- list(new("nullSymMatrix")))
	ifelse(contain(4, position), VTE <- List[position == 4], VTE <- list(new("nullSimVector")))
	ifelse(contain(5, position), VY <- List[position == 5], VY <- list(new("nullSimVector")))
	if(!is.null.object(VTE[[1]]) & !is.null.object(VY[[1]])) stop("Please assign either VTE or VY, not both")
	ifelse(contain(8, position), MY <- List[position == 8], MY <- list(new("nullSimVector")))
	ifelse(contain(6, position), TY <- List[position == 6], TY <- list(new("nullSimVector")))
	if(!is.null.object(MY[[1]]) & !is.null.object(TY[[1]])) stop("Please assign either MY or TY, not both")
	ifelse(contain(7, position), ME <- List[position == 7], ME <- list(new("nullSimVector")))
	ifelse(contain(9, position), VE <- List[position == 9], VE <- list(new("nullSimVector")))
	Output <- new("simMisspecifiedSet", LY=LY[[1]], PS=PS[[1]], TE=TE[[1]], VE=VE[[1]], VPS=VE[[1]], VTE=VTE[[1]], VY=VY[[1]], TY=TY[[1]], MY=MY[[1]], ME=ME[[1]], AL=ME[[1]], Tag="CFA")
	return(Output)
}
